import {
  pgTable,
  text,
  timestamp,
  boolean,
  varchar,
  integer,
} from "drizzle-orm/pg-core";
import * as authSchema from "./auth-schema"; // auth schema auto generated by better-auth
import { relations } from "drizzle-orm";

export const {
  account,
  accountRelations,
  session,
  sessionRelations,
  user,
  userRelations,
  verification,
} = authSchema;

export const product = pgTable("products", {
  id: text("id").primaryKey(),
  name: varchar("name", { length: 128 }).notNull(),
  shortDescription: varchar("short_description", {
    length: 128,
  }).notNull(),
  fullDescription: text("full_description").default(""),
  type: text("type", {
    enum: ["goods", "services", "goods_and_services"],
  }).notNull(),
  image: text().default(""),
  isStockReady: boolean("is_stock_ready").default(true),
  userId: text("user_id")
    .references(() => user.id, { onDelete: "cascade" })
    .notNull(),
  categoryId: text("category_id")
    .references(() => category.id, { onDelete: "cascade" })
    .notNull(),
  price: integer().notNull(),
  discountPrice: integer().$defaultFn(() => 0),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const category = pgTable("categories", {
  id: text("id").primaryKey(),
  name: varchar("name", { length: 32 }).notNull().unique(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const feed = pgTable("feed", {
  id: text("id").primaryKey(),
  text: text().default(""),
  image: text().default(""),
  userId: text("user_id")
    .references(() => user.id, { onDelete: "cascade" })
    .notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const productOnFeed = pgTable("product_on_feed", {
  id: text("id").primaryKey(),
  productId: text()
    .references(() => product.id, { onDelete: "cascade" })
    .notNull(),
  feedId: text()
    .references(() => feed.id, { onDelete: "cascade" })
    .notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const cart = pgTable("carts", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .references(() => user.id, { onDelete: "cascade" })
    .notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const cartItem = pgTable("cart_items", {
  id: text("id").primaryKey(),
  cartId: text("cart_id")
    .references(() => cart.id, { onDelete: "cascade" })
    .notNull(),
  productId: text("product_id")
    .references(() => product.id, { onDelete: "cascade" })
    .notNull(),
  quantity: integer("quantity").notNull().default(1),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const order = pgTable("orders", {
  id: text("id").primaryKey(),

  userId: text("user_id")
    .references(() => user.id, { onDelete: "cascade" })
    .notNull(),

  // if buy-now, 1 item; if cart-checkout, multiple items
  totalAmount: integer("total_amount").notNull(),

  status: text("status", {
    enum: [
      "pending",
      "awaiting_payment",
      "paid",
      "shipping",
      "completed",
      "cancelled",
    ],
  }).default("pending"),

  shippingNumber: varchar("shipping_number", { length: 64 }),

  merchantNote: text("merchant_note").default(""), // optional: merchant notes

  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

export const orderItem = pgTable("order_items", {
  id: text("id").primaryKey(),

  orderId: text("order_id")
    .references(() => order.id, { onDelete: "cascade" })
    .notNull(),

  productId: text("product_id")
    .references(() => product.id, { onDelete: "cascade" })
    .notNull(),

  quantity: integer("quantity").notNull().default(1),
  priceAtPurchase: integer("price_at_purchase").notNull(),
});

export const cartRelation = relations(cart, ({ many }) => ({
  items: many(cartItem),
}));

export const cartItemRelation = relations(cartItem, ({ one }) => ({
  cart: one(cart, {
    fields: [cartItem.cartId],
    references: [cart.id],
  }),
  product: one(product, {
    fields: [cartItem.productId],
    references: [product.id],
  }),
}));
