/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as FeedsRouteImport } from './routes/feeds'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CartsIndexRouteImport } from './routes/carts/index'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as DashboardMerchantIndexRouteImport } from './routes/dashboard/merchant/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardMerchantKatalogRouteImport } from './routes/dashboard/merchant/katalog'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardMerchantOrdersIndexRouteImport } from './routes/dashboard/merchant/orders/index'
import { Route as DashboardAdminUsersIndexRouteImport } from './routes/dashboard/admin/users/index'

const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsRoute = FeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CartsIndexRoute = CartsIndexRouteImport.update({
  id: '/carts/',
  path: '/carts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMerchantIndexRoute = DashboardMerchantIndexRouteImport.update({
  id: '/merchant/',
  path: '/merchant/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMerchantKatalogRoute =
  DashboardMerchantKatalogRouteImport.update({
    id: '/merchant/katalog',
    path: '/merchant/katalog',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMerchantOrdersIndexRoute =
  DashboardMerchantOrdersIndexRouteImport.update({
    id: '/merchant/orders/',
    path: '/merchant/orders/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdminUsersIndexRoute =
  DashboardAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/feeds': typeof FeedsRoute
  '/setting': typeof SettingRoute
  '/products/$id': typeof ProductsIdRoute
  '/carts': typeof CartsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/merchant/katalog': typeof DashboardMerchantKatalogRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/merchant': typeof DashboardMerchantIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersIndexRoute
  '/dashboard/merchant/orders': typeof DashboardMerchantOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feeds': typeof FeedsRoute
  '/setting': typeof SettingRoute
  '/products/$id': typeof ProductsIdRoute
  '/carts': typeof CartsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/merchant/katalog': typeof DashboardMerchantKatalogRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/merchant': typeof DashboardMerchantIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersIndexRoute
  '/dashboard/merchant/orders': typeof DashboardMerchantOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/feeds': typeof FeedsRoute
  '/setting': typeof SettingRoute
  '/products/$id': typeof ProductsIdRoute
  '/carts/': typeof CartsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/merchant/katalog': typeof DashboardMerchantKatalogRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/merchant/': typeof DashboardMerchantIndexRoute
  '/dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
  '/dashboard/merchant/orders/': typeof DashboardMerchantOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth'
    | '/feeds'
    | '/setting'
    | '/products/$id'
    | '/carts'
    | '/dashboard/'
    | '/orders'
    | '/products'
    | '/api/auth/$'
    | '/dashboard/merchant/katalog'
    | '/dashboard/admin'
    | '/dashboard/merchant'
    | '/dashboard/admin/users'
    | '/dashboard/merchant/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feeds'
    | '/setting'
    | '/products/$id'
    | '/carts'
    | '/dashboard'
    | '/orders'
    | '/products'
    | '/api/auth/$'
    | '/dashboard/merchant/katalog'
    | '/dashboard/admin'
    | '/dashboard/merchant'
    | '/dashboard/admin/users'
    | '/dashboard/merchant/orders'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth'
    | '/feeds'
    | '/setting'
    | '/products/$id'
    | '/carts/'
    | '/dashboard/'
    | '/orders/'
    | '/products/'
    | '/api/auth/$'
    | '/dashboard/merchant/katalog'
    | '/dashboard/admin/'
    | '/dashboard/merchant/'
    | '/dashboard/admin/users/'
    | '/dashboard/merchant/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeedsRoute: typeof FeedsRoute
  SettingRoute: typeof SettingRoute
  ProductsIdRoute: typeof ProductsIdRoute
  CartsIndexRoute: typeof CartsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds': {
      id: '/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/carts/': {
      id: '/carts/'
      path: '/carts'
      fullPath: '/carts'
      preLoaderRoute: typeof CartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/merchant/': {
      id: '/dashboard/merchant/'
      path: '/merchant'
      fullPath: '/dashboard/merchant'
      preLoaderRoute: typeof DashboardMerchantIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/merchant/katalog': {
      id: '/dashboard/merchant/katalog'
      path: '/merchant/katalog'
      fullPath: '/dashboard/merchant/katalog'
      preLoaderRoute: typeof DashboardMerchantKatalogRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/merchant/orders/': {
      id: '/dashboard/merchant/orders/'
      path: '/merchant/orders'
      fullPath: '/dashboard/merchant/orders'
      preLoaderRoute: typeof DashboardMerchantOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/users/': {
      id: '/dashboard/admin/users/'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMerchantKatalogRoute: typeof DashboardMerchantKatalogRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardMerchantIndexRoute: typeof DashboardMerchantIndexRoute
  DashboardAdminUsersIndexRoute: typeof DashboardAdminUsersIndexRoute
  DashboardMerchantOrdersIndexRoute: typeof DashboardMerchantOrdersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMerchantKatalogRoute: DashboardMerchantKatalogRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardMerchantIndexRoute: DashboardMerchantIndexRoute,
  DashboardAdminUsersIndexRoute: DashboardAdminUsersIndexRoute,
  DashboardMerchantOrdersIndexRoute: DashboardMerchantOrdersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FeedsRoute: FeedsRoute,
  SettingRoute: SettingRoute,
  ProductsIdRoute: ProductsIdRoute,
  CartsIndexRoute: CartsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
